
import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Book as BookIcon, 
  History, 
  User, 
  ChevronLeft, 
  Download, 
  Trash2, 
  Printer, 
  Sparkles, 
  ArrowRight,
  Github,
  Twitter,
  ExternalLink,
  CheckCircle2,
  Info
} from 'lucide-react';
import { Book, GenerationStep, Page } from './types';
import { generateBookOutline, generateChapterContent, generateCoverOptions } from './services/geminiService';
import { Button } from './components/Button';

// Utility for safe ID generation
const generateId = () => {
  try {
    return crypto.randomUUID();
  } catch {
    return Math.random().toString(36).substring(2, 15);
  }
};

const App: React.FC = () => {
  const [currentPage, setCurrentPage] = useState<Page>('home');
  const [titleInput, setTitleInput] = useState('');
  const [authorInput, setAuthorInput] = useState('');
  const [step, setStep] = useState<GenerationStep>('idle');
  const [book, setBook] = useState<Book | null>(null);
  const [tempBookData, setTempBookData] = useState<any>(null);
  const [availableCovers, setAvailableCovers] = useState<string[]>([]);
  const [progress, setProgress] = useState(0);
  const [history, setHistory] = useState<Book[]>([]);

  // Load history from local storage safely
  useEffect(() => {
    const saved = localStorage.getItem('bookmass_history_v2');
    if (saved) {
      try {
        const parsed = JSON.parse(saved);
        if (Array.isArray(parsed)) setHistory(parsed);
      } catch (e) {
        console.error("Failed to parse history", e);
      }
    }
  }, []);

  const saveToHistory = (newBook: Book) => {
    const updated = [newBook, ...history.filter(b => b.id !== newBook.id)].slice(0, 20); // Keep last 20
    setHistory(updated);
    localStorage.setItem('bookmass_history_v2', JSON.stringify(updated));
  };

  const deleteFromHistory = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    const updated = history.filter(b => b.id !== id);
    setHistory(updated);
    localStorage.setItem('bookmass_history_v2', JSON.stringify(updated));
  };

  const handleGenerate = async () => {
    if (!titleInput.trim() || !authorInput.trim()) return;

    setStep('outlining');
    setProgress(10);
    setBook(null);
    setCurrentPage('home');

    try {
      const outline = await generateBookOutline(titleInput, authorInput);
      setProgress(25);

      setStep('painting');
      const covers = await generateCoverOptions(
        String(outline.title || titleInput), 
        String(outline.genre || 'General'), 
        String(outline.description || '')
      );
      setAvailableCovers(covers);
      setProgress(40);

      setStep('writing');
      const chaptersWithContent = [];
      const chaptersList = outline.chapters || [];
      const totalChapters = chaptersList.length;

      for (let i = 0; i < totalChapters; i++) {
        const chapter = chaptersList[i];
        const content = await generateChapterContent(String(outline.title || titleInput), chapter);
        chaptersWithContent.push({ ...chapter, content: String(content) });
        setProgress(40 + ((i + 1) / totalChapters) * 55);
      }

      setTempBookData({
        title: String(outline.title || titleInput),
        author: String(authorInput),
        genre: String(outline.genre || 'Uncategorized'),
        description: String(outline.description || 'Generated by BookMass AI Factory'),
        chapters: chaptersWithContent,
      });

      setStep('selecting-cover');
      setProgress(100);
    } catch (error) {
      console.error(error);
      setStep('error');
    }
  };

  const finalizeBook = (selectedCover: string) => {
    if (!tempBookData) return;
    
    const finalBook: Book = {
      id: generateId(),
      title: tempBookData.title,
      author: tempBookData.author,
      genre: tempBookData.genre,
      coverImageUrl: selectedCover,
      availableCovers: availableCovers,
      description: tempBookData.description,
      chapters: tempBookData.chapters,
      createdAt: Date.now(),
    };

    setBook(finalBook);
    saveToHistory(finalBook);
    setStep('completed');
  };

  const downloadTextFile = (b: Book) => {
    try {
      let text = `${String(b.title).toUpperCase()}\n`;
      text += `Written by ${String(b.author)}\n`;
      text += `Genre: ${String(b.genre)}\n`;
      text += `Published by BookMass AI Factory\n`;
      text += `------------------------------------------\n\n`;
      text += `SUMMARY: ${String(b.description)}\n\n`;
      
      b.chapters.forEach(c => {
        text += `\n\nCHAPTER ${c.id}: ${String(c.title).toUpperCase()}\n`;
        text += `==========================================\n\n`;
        text += `${String(c.content)}\n\n`;
      });
      
      const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${b.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.txt`;
      document.body.appendChild(link);
      link.click();
      setTimeout(() => {
        document.body.removeChild(link);
        window.URL.revokeObjectURL(url);
      }, 100);
    } catch (err) {
      alert("Download failed. Please try saving as PDF instead.");
    }
  };

  const pageVariants = {
    initial: { opacity: 0, y: 10 },
    animate: { opacity: 1, y: 0 },
    exit: { opacity: 0, y: -10 }
  };

  const renderContent = () => {
    if (step === 'selecting-cover') {
      return (
        <motion.div initial="initial" animate="animate" variants={pageVariants} className="w-full max-w-5xl text-center px-4">
          <h2 className="text-4xl font-bold heading-font mb-4">Choose Your Aesthetics</h2>
          <p className="text-slate-500 mb-12 max-w-lg mx-auto">Select the cover that best represents your vision.</p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {availableCovers.map((cover, idx) => (
              <motion.div 
                key={idx}
                whileHover={{ y: -8 }}
                className="group cursor-pointer"
                onClick={() => finalizeBook(cover)}
              >
                <div className="aspect-[3/4] rounded-2xl overflow-hidden shadow-2xl border-4 border-transparent group-hover:border-indigo-500 transition-all bg-slate-100">
                  <img src={cover} className="w-full h-full object-cover" alt={`Concept ${idx+1}`} />
                  <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                    <span className="bg-white text-indigo-600 px-6 py-2 rounded-full font-bold">Select Style</span>
                  </div>
                </div>
                <p className="mt-4 font-black text-slate-400 uppercase tracking-widest text-[10px]">Concept 0{idx+1}</p>
              </motion.div>
            ))}
          </div>
        </motion.div>
      );
    }

    if (step === 'completed' && book) {
      return (
        <motion.div initial="initial" animate="animate" variants={pageVariants} className="w-full max-w-4xl pb-20">
          <div className="flex flex-col md:flex-row gap-12 items-start mb-24 no-print">
            <div className="w-full md:w-1/2">
              <img src={book.coverImageUrl} className="rounded-2xl shadow-2xl w-full aspect-[3/4] object-cover" alt="Selected Cover" />
            </div>
            <div className="w-full md:w-1/2 space-y-6">
               <span className="px-4 py-1 bg-indigo-50 text-indigo-700 rounded-full text-xs font-bold uppercase tracking-widest">{String(book.genre)}</span>
               <h2 className="text-5xl font-black heading-font leading-tight">{String(book.title)}</h2>
               <p className="text-xl text-slate-400 italic">by {String(book.author)}</p>
               <p className="text-slate-600 leading-relaxed text-lg">{String(book.description)}</p>
               <div className="flex flex-wrap gap-4 pt-6">
                  <Button onClick={() => window.print()} className="flex-1 min-w-[140px]"><Printer size={18}/> Print/PDF</Button>
                  <Button onClick={() => downloadTextFile(book)} variant="outline" className="flex-1 min-w-[140px]"><Download size={18}/> Download TXT</Button>
               </div>
            </div>
          </div>
          
          <div className="space-y-24">
            {book.chapters.map(c => (
              <section key={c.id} className="serif-font max-w-2xl mx-auto print-page-break px-4">
                <div className="text-center mb-12">
                   <p className="text-indigo-500 font-bold uppercase tracking-[0.3em] text-[10px] mb-2">Chapter {c.id}</p>
                   <h3 className="text-4xl font-bold">{String(c.title)}</h3>
                   <div className="w-12 h-0.5 bg-indigo-100 mx-auto mt-6"></div>
                </div>
                <div className="text-lg text-slate-800 leading-relaxed space-y-6">
                  {String(c.content).split('\n').map((p, i) => p.trim() && <p key={i}>{p}</p>)}
                </div>
              </section>
            ))}
          </div>
        </motion.div>
      );
    }

    switch(currentPage) {
      case 'about':
        return (
          <motion.div initial="initial" animate="animate" variants={pageVariants} className="max-w-4xl w-full space-y-16 px-4 py-10">
            <div className="text-center space-y-4">
              <h2 className="text-6xl font-black heading-font tracking-tighter">About BookMass</h2>
              <p className="text-xl text-slate-500 max-w-xl mx-auto">The world's most sophisticated AI-powered book manufacturing engine.</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="p-10 bg-white border border-slate-100 rounded-[2.5rem] shadow-sm">
                <Sparkles className="text-indigo-600 mb-6" size={32}/>
                <h4 className="text-2xl font-bold mb-4">Pure Intelligence</h4>
                <p className="text-slate-500 leading-relaxed">Leveraging Gemini 3.0 Pro reasoning for deep narrative structure and character consistency.</p>
              </div>
              <div className="p-10 bg-indigo-600 text-white rounded-[2.5rem] shadow-xl">
                <BookIcon className="text-indigo-200 mb-6" size={32}/>
                <h4 className="text-2xl font-bold mb-4">Visual Storytelling</h4>
                <p className="text-indigo-100 leading-relaxed">Integrated image generation offers three unique aesthetic concepts for every manuscript created.</p>
              </div>
            </div>
          </motion.div>
        );
      case 'developer':
        return (
          <motion.div initial="initial" animate="animate" variants={pageVariants} className="flex flex-col items-center text-center space-y-10 px-4 py-10 w-full">
            <div className="relative">
              <div className="absolute inset-0 bg-indigo-500 blur-[80px] opacity-20"></div>
              <div className="w-56 h-56 rounded-[3rem] overflow-hidden border-4 border-white shadow-2xl relative z-10">
                <img 
                  src="https://raw.githubusercontent.com/gforg5/Nano-Lens/refs/heads/main/1769069098374.png" 
                  className="w-full h-full object-cover" 
                  alt="Sayed Mohsin Ali"
                />
              </div>
            </div>
            <div className="space-y-4">
              <h2 className="text-4xl font-black heading-font">Sayed Mohsin Ali</h2>
              <p className="px-6 py-1.5 bg-indigo-600 text-white rounded-full text-[10px] font-black uppercase tracking-[0.2em] inline-block">Systems Developer</p>
            </div>
            <p className="max-w-md text-xl text-slate-500 italic font-medium leading-relaxed">
              "Building robust digital ecosystems where software meets creativity."
            </p>
            <div className="flex gap-4">
               {[Github, Twitter, ExternalLink].map((Icon, i) => (
                 <a key={i} href="#" className="p-4 bg-white border border-slate-100 rounded-2xl text-slate-400 hover:text-indigo-600 transition-all shadow-sm">
                    <Icon size={20}/>
                 </a>
               ))}
            </div>
          </motion.div>
        );
      case 'history':
        return (
          <motion.div initial="initial" animate="animate" variants={pageVariants} className="w-full max-w-5xl px-4 py-10">
            <h2 className="text-4xl font-black heading-font mb-10">Factory Archive</h2>
            {history.length === 0 ? (
              <div className="text-center py-20 bg-slate-50 rounded-[2.5rem] border-2 border-dashed border-slate-200">
                <p className="text-slate-400 font-bold">Your library is currently empty.</p>
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                {history.map(b => (
                  <motion.div 
                    key={b.id} 
                    className="flex bg-white rounded-[2rem] shadow-sm border border-slate-100 overflow-hidden group hover:shadow-xl transition-all cursor-pointer"
                    onClick={() => { setBook(b); setStep('completed'); }}
                  >
                    <img src={b.coverImageUrl} className="w-32 h-full object-cover" alt="Cover" />
                    <div className="p-6 flex flex-col justify-between flex-1">
                      <div>
                        <h4 className="font-black text-lg line-clamp-1 heading-font">{String(b.title)}</h4>
                        <p className="text-xs text-slate-400 font-bold">By {String(b.author)}</p>
                      </div>
                      <div className="flex justify-between items-center pt-4">
                        <span className="text-[10px] font-bold text-indigo-600 uppercase">View Manuscript</span>
                        <button 
                          onClick={(e) => deleteFromHistory(b.id, e)}
                          className="p-2 text-slate-200 hover:text-rose-500 transition-colors"
                        ><Trash2 size={16}/></button>
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>
            )}
          </motion.div>
        );
      default: // HOME
        if (step === 'idle') {
          return (
            <motion.main initial="initial" animate="animate" variants={pageVariants} className="w-full max-w-2xl text-center space-y-12 py-10 px-4">
              <div className="space-y-4">
                <h2 className="text-7xl font-black heading-font tracking-tighter leading-tight">
                  BookMass <br/>
                  <span className="text-indigo-600">Publishing.</span>
                </h2>
                <p className="text-lg text-slate-500 max-w-md mx-auto">
                  The quickest way to transition from an idea to a full manuscript with custom covers.
                </p>
              </div>

              <div className="bg-white p-8 md:p-12 rounded-[3rem] shadow-2xl shadow-indigo-100 border border-slate-50 space-y-6 text-left">
                <div className="space-y-2">
                  <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Author Name</label>
                  <input 
                    type="text" 
                    placeholder="e.g. Sayed Mohsin Ali"
                    className="w-full px-6 py-4 rounded-2xl bg-slate-50 border-2 border-slate-50 focus:bg-white focus:border-indigo-500 outline-none transition-all font-bold"
                    value={authorInput}
                    onChange={(e) => setAuthorInput(e.target.value)}
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Book Title</label>
                  <input 
                    type="text" 
                    placeholder="e.g. The Architecture of Silence"
                    className="w-full px-6 py-4 rounded-2xl bg-slate-50 border-2 border-slate-50 focus:bg-white focus:border-indigo-500 outline-none transition-all font-bold"
                    value={titleInput}
                    onChange={(e) => setTitleInput(e.target.value)}
                    onKeyDown={(e) => e.key === 'Enter' && handleGenerate()}
                  />
                </div>
                <Button className="w-full py-5 text-xl font-black rounded-2xl" onClick={handleGenerate} disabled={!titleInput || !authorInput}>
                  Generate Manuscript
                </Button>
              </div>
            </motion.main>
          );
        }
        
        return (
          <div className="w-full max-w-md text-center py-24 space-y-8">
             <div className="relative w-24 h-24 mx-auto">
                <div className="absolute inset-0 border-8 border-indigo-50 rounded-full"></div>
                <motion.div 
                  className="absolute inset-0 border-8 border-indigo-600 rounded-full border-t-transparent"
                  animate={{ rotate: 360 }}
                  transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                ></motion.div>
             </div>
             <div className="space-y-2">
                <h3 className="text-2xl font-black heading-font">
                  {step === 'outlining' && "Building Narrative Core..."}
                  {step === 'painting' && "Visualising Themes..."}
                  {step === 'writing' && "Streaming Chapters..."}
                </h3>
                <div className="w-full bg-slate-100 h-1.5 rounded-full overflow-hidden mt-6">
                   <motion.div className="bg-indigo-600 h-full" animate={{ width: `${progress}%` }} />
                </div>
                <p className="text-slate-400 font-bold text-xs uppercase tracking-widest pt-2">{Math.round(progress)}% Processed</p>
             </div>
          </div>
        );
    }
  };

  return (
    <div className="min-h-screen bg-white">
      <nav className="fixed top-0 left-0 right-0 h-24 glass z-50 px-6 md:px-12 flex items-center justify-between no-print">
        <div className="flex items-center gap-4 cursor-pointer" onClick={() => { setStep('idle'); setCurrentPage('home'); }}>
          <div className="w-12 h-12 bg-indigo-600 rounded-2xl flex items-center justify-center text-white shadow-lg">
             <BookIcon size={24}/>
          </div>
          <div className="hidden sm:flex flex-col">
            <span className="text-xl font-black heading-font text-slate-900 leading-none">BookMass</span>
            <span className="text-[10px] font-black uppercase tracking-[0.2em] text-indigo-600">AI Factory</span>
          </div>
        </div>

        <div className="flex items-center gap-6">
          <button onClick={() => setCurrentPage('history')} className={`font-black text-[10px] uppercase tracking-widest ${currentPage === 'history' ? 'text-indigo-600' : 'text-slate-400'}`}>Archive</button>
          <button onClick={() => setCurrentPage('about')} className={`font-black text-[10px] uppercase tracking-widest ${currentPage === 'about' ? 'text-indigo-600' : 'text-slate-400'}`}>About</button>
          <button onClick={() => setCurrentPage('developer')} className={`font-black text-[10px] uppercase tracking-widest ${currentPage === 'developer' ? 'text-indigo-600' : 'text-slate-400'}`}>Dev</button>
        </div>
      </nav>

      <div className="pt-32 flex flex-col items-center">
        <AnimatePresence mode="wait">
          {renderContent()}
        </AnimatePresence>
      </div>

      <footer className="py-20 border-t border-slate-50 text-center no-print">
         <p className="text-slate-400 font-black heading-font tracking-[0.4em] uppercase text-[10px] mb-2">Systems Architect</p>
         <h4 className="text-slate-900 font-black heading-font text-lg">Sayed Mohsin Ali Systems Developer</h4>
         <p className="text-slate-300 text-[10px] uppercase tracking-widest mt-6">&copy; 2024 BookMass All Rights Reserved</p>
      </footer>
    </div>
  );
};

export default App;
